const list = [
  {
    id: '0',
    diffNoon: '上午',
    lesMon: {
      lesId: '1001',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第一节',
    lesTue: {
      lesId: '10010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '10011112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '1',
    diffNoon: '上午',
    lesMon: {
      lesId: '101f01',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第二节',
    lesTue: {
      lesId: '10cs010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100dq111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10d2011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '100da11112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001gd111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100vd111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '2',
    diffNoon: '上午',
    lesMon: {
      lesId: '102v01',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第三节',
    lesTue: {
      lesId: '10fs10',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '1001fs11',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '100gd11',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '1001nng1112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '100vf1111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100bd111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '3',
    diffNoon: '上午',
    lesMon: {
      lesId: '1001',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第四节',
    lesTue: {
      lesId: '10010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '10011112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '30215',
    diffNoon: '上午',
    lesMon: {
      lesId: '1001',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第五节',
    lesTue: {
      lesId: '10010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '10011112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '4',
    diffNoon: '下午',
    lesMon: {
      lesId: '1001',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第六节',
    lesTue: {
      lesId: '10010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '10011112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
  {
    id: '5',
    diffNoon: '下午',
    lesMon: {
      lesId: '1001',
      lesPlace: '701',
      lesSub: '语文',
      lesStu: '120',
      lesTeacher: '李老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesType: '正常',
    lesSort: '第七节',
    lesTue: {
      lesId: '10010',
      lesPlace: '701',
      lesSub: '数学',
      lesStu: '100',
      lesTeacher: '刘老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesWed: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesThu: {
      lesId: '10011',
      lesPlace: '701',
      lesSub: '英语',
      lesStu: '150',
      lesTeacher: '陈老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesFri: {
      lesId: '10011112',
      lesPlace: '701',
      lesSub: '化学',
      lesStu: '70',
      lesTeacher: '周老师',
      lesSort: '第一节',
      isHoliday: false,
    },
    lesSat: {
      lesId: '1001111',
      lesPlace: '701',
      lesSub: '生物',
      lesStu: '70',
      lesTeacher: '孙老师',
      lesSort: '第一节',
      isHoliday: true,
    },
    lesSun: {
      lesId: '100111',
      lesPlace: '701',
      lesSub: '物理',
      lesStu: '1400',
      lesTeacher: '赵老师',
      lesSort: '第一节',
      isHoliday: true,
    },
  },
]
const rule = [
  {
    id: '0',
    diffNoon: '上午',
    lesMon: {
      lesId: '1001',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesType: '正常',
    lesSort: '第一节',
    lesTue: {
      lesId: '10010',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesWed: {
      lesId: '100111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesThu: {
      lesId: '10011',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesFri: {
      lesId: '10011112',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesSat: {
      lesId: '1001111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
    lesSun: {
      lesId: '100111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '1',
          ruleWeight: '1',
          useObject: '美术'
        }
      ]
    },
  },
  {
    id: '1',
    diffNoon: '上午',
    lesMon: {
      lesId: '101f01',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
    lesType: '正常',
    lesSort: '第二节',
    lesTue: {
      lesId: '10cs010',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        },
        {
          ruleId: '34344',
          rules: '3',
          ruleWeight: '1',
          useObject: '王倩'
        },
        {
          ruleId: '1312',
          rules: '4',
          ruleWeight: '1',
          useObject: '婷儿'
        },
        {
          ruleId: '1312',
          rules: '4',
          ruleWeight: '1',
          useObject: '婷儿'
        },
        {
          ruleId: '1312',
          rules: '4',
          ruleWeight: '1',
          useObject: '婷儿'
        },
        {
          ruleId: '1312',
          rules: '4',
          ruleWeight: '1',
          useObject: '婷儿'
        },
        {
          ruleId: '1312',
          rules: '4',
          ruleWeight: '1',
          useObject: '婷儿'
        },
      ]
    },
    lesWed: {
      lesId: '100dq111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
    lesThu: {
      lesId: '10d2011',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
    lesFri: {
      lesId: '100da11112',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
    lesSat: {
      lesId: '1001gd111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
    lesSun: {
      lesId: '100vd111',
      ruleList: [
        {
          ruleId: '1312',
          rules: '2',
          ruleWeight: '1',
          useObject: '音乐'
        }
      ]
    },
  },
]
const treeData = [
  {
    placeCode: '0',
    placeName: '成都市第七中学',
    placeType: '1',
    parentCode: '',
    children: [
      {
        placeCode: '0-1',
        placeName: '1栋教学楼',
        placeType: '2',
        parentCode: '0',
        children: [
          {
            placeCode: '0-1-0',
            placeName: '一楼',
            placeType: '3',
            parentCode: '0-1',
            children: [
              {
                placeCode: '0-1-0-1',
                placeName: '1-101',
                placeType: '4',
                parentCode: '0-1-0',
              },
              {
                placeCode: '0-1-0-2',
                placeName: '1-102',
                placeType: '4',
                parentCode: '0-1-0',
              },
              {
                placeCode: '0-1-0-3',
                placeName: '1-103',
                placeType: '4',
                parentCode: '0-1-0',
              },
            ],
          },
          {
            placeCode: '0-1-1',
            placeName: '二楼',
            placeType: '3',
            parentCode: '0-1',
            children: [
              {
                placeCode: '0-1-1-1',
                placeName: '2-101',
                placeType: '4',
                parentCode: '0-1-1',
              },
              {
                placeCode: '0-1-1-2',
                placeName: '2-102',
                placeType: '4',
                parentCode: '0-1-1',
              },
              {
                placeCode: '0-1-1-3',
                placeName: '2-103',
                placeType: '4',
                parentCode: '0-1-1',
              },
            ],
          },
          {
            placeCode: '0-1-2',
            placeName: '三楼',
            placeType: '3',
            parentCode: '0-1',
            children: [
              {
                placeCode: '0-1-2-1',
                placeName: '2-101',
                placeType: '4',
                parentCode: '0-1-2',
              },
              {
                placeCode: '0-1-2-2',
                placeName: '2-102',
                placeType: '4',
                parentCode: '0-1-2',
              },
              {
                placeCode: '0-1-2-3',
                placeName: '2-103',
                placeType: '4',
                parentCode: '0-1-2',
              },
              {
                placeCode: '0-1-2-4',
                placeName: '2-104',
                placeType: '4',
                parentCode: '0-1-2',
              },
            ],
          },
        ],
      },
      {
        placeCode: '0-2',
        placeName: '2栋教学楼',
        placeType: '2',
        parentCode: '0',
        children: [
          {
            placeCode: '0-2-0',
            placeName: '一楼',
            placeType: '3',
            parentCode: '0-2',
            children: [
              {
                placeCode: '0-2-0-1',
                placeName: '1-101',
                placeType: '4',
                parentCode: '0-2-0',
              },
              {
                placeCode: '0-2-0-2',
                placeName: '1-102',
                placeType: '4',
                parentCode: '0-2-0',
              },
              {
                placeCode: '0-2-0-3',
                placeName: '1-103',
                placeType: '4',
                parentCode: '0-2-0',
              },
            ],
          },
          {
            placeCode: '0-2-1',
            placeName: '二楼',
            placeType: '3',
            parentCode: '0-2',
            children: [
              {
                placeCode: '0-2-1-1',
                placeName: '2-101',
                placeType: '4',
                parentCode: '0-2-1',
              },
              {
                placeCode: '0-2-1-2',
                placeName: '2-102',
                placeType: '4',
                parentCode: '0-2-1',
              },
              {
                placeCode: '0-2-1-3',
                placeName: '2-103',
                placeType: '4',
                parentCode: '0-2-1',
              },
            ],
          },
          {
            placeCode: '0-2-2',
            placeName: '三楼',
            placeType: '3',
            parentCode: '0-2',
            children: [
              {
                placeCode: '0-2-2-1',
                placeName: '2-101',
                placeType: '4',
                parentCode: '0-2-2',
              },
              {
                placeCode: '0-2-2-2',
                placeName: '2-102',
                placeType: '4',
                parentCode: '0-2-2',
              },
              {
                placeCode: '0-2-2-3',
                placeName: '2-103',
                placeType: '4',
                parentCode: '0-2-2',
              },
            ],
          },
        ],
      },
    ],
  },
]

const grade = [
  {
    id: '0',
    diffNoon: '上午',
    lesMon: [
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesType: '正常',
    lesSort: '第一节',
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: '01',
    diffNoon: '上午',
    lesType: '正常',
    lesSort: '第二节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: 'dw01',
    diffNoon: '上午',
    lesType: '正常',
    lesSort: '第三节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: '0152',
    diffNoon: '上午',
    lesType: '正常',
    lesSort: '第四节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: '0111d',
    diffNoon: '上午',
    lesType: '正常',
    lesSort: '第五节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: '015572',
    diffNoon: '下午',
    lesType: '正常',
    lesSort: '第六节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
  {
    id: '0545851',
    diffNoon: '下午',
    lesType: '正常',
    lesSort: '第七节',
    lesMon: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesTue: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesWed: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesThu: [
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001aw',
        lesPlace: '704',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '1001d1',
        lesPlace: '701',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesFri: [
      {
        lesId: '1001d',
        lesPlace: '701',
        lesSub: '语文',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100112',
        lesPlace: '702',
        lesSub: '数学',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
      {
        lesId: '100dw',
        lesPlace: '703',
        lesSub: '英语',
        lesStu: '120',
        lesTeacher: '李老师',
        lesSort: '第一节',
        isHoliday: false,
      },
    ],
    lesSat: [],
    lesSun: [],
  },
]
export { list, treeData, grade, rule }
